import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '@/styles/globals.css'
import Navbar from '@/components/Navbar'



const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'MY APPLICATION',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-slate-300 max-w-7xl`}>
        <Navbar />
        <div className='p-4'>
          {children}

        </div>
          </body>
    </html>
  )
}
